/** Unlinked mentions of a note (its title or aliases as plain text elsewhere) and one-click linking. */
import { findMentions, linkMention, parseFrontmatter } from '@corpobrain/core';
import { Hono } from 'hono';
import { HttpError, type VaultService } from './vault-service.ts';

function namesOf(v: VaultService, path: string): { title: string; names: string[] } {
  const row = v.indexer.db
    .prepare('SELECT title, frontmatter_json FROM notes WHERE path = ?')
    .get(path) as { title: string; frontmatter_json: string } | undefined;
  if (!row) throw new HttpError(404, `not indexed: ${path}`);
  let aliases: string[] = [];
  try {
    const fm = JSON.parse(row.frontmatter_json) as { aliases?: unknown };
    if (Array.isArray(fm.aliases))
      aliases = fm.aliases.filter((a): a is string => typeof a === 'string');
  } catch {
    /* none */
  }
  return { title: row.title, names: [row.title, ...aliases].filter((n) => n.trim().length >= 2) };
}

export function mentionsRoutes(v: VaultService): Hono {
  const app = new Hono();

  app.get('/', (c) => {
    const path = c.req.query('path');
    if (!path) throw new HttpError(400, 'path required');
    const { title, names } = namesOf(v, path);
    if (!names.length) return c.json({ title, names, mentions: [] });
    // candidates from full-text search (phrase per name), minus self, minus
    // notes that already link here, minus Jira mirrors (regenerated by sync)
    const linking = new Set(
      (
        v.indexer.db
          .prepare('SELECT DISTINCT src_path FROM links WHERE dst_path = ?')
          .all(path) as {
          src_path: string;
        }[]
      ).map((r) => r.src_path),
    );
    const jiraPrefix = `${v.config.folders.jira}/`;
    const candidates = new Map<string, string>();
    for (const name of names) {
      for (const hit of v.indexer.search(name, 60)) {
        if (hit.path === path || linking.has(hit.path) || hit.path.startsWith(jiraPrefix)) continue;
        candidates.set(hit.path, hit.title);
      }
    }
    const mentions: { path: string; title: string; line: number; snippet: string; name: string }[] =
      [];
    for (const [p, t] of candidates) {
      let content: string;
      try {
        content = v.read(p).content;
      } catch {
        continue;
      }
      const [first] = findMentions(content, names, 1);
      if (!first) continue;
      mentions.push({
        path: p,
        title: t,
        line: first.line,
        snippet: first.lineText.trim().slice(0, 160),
        name: first.name,
      });
      if (mentions.length >= 30) break;
    }
    mentions.sort((a, b) => a.title.localeCompare(b.title));
    return c.json({ title, names, mentions });
  });

  /** Turn the first plain mention of `target` in `source` into a [[link]]. */
  app.post('/link', async (c) => {
    const body = (await c.req.json()) as { source?: string; target?: string };
    if (!body.source || !body.target) throw new HttpError(400, 'source and target required');
    const { title, names } = namesOf(v, body.target);
    const { path, content } = v.read(body.source);
    if (parseFrontmatter(content).error)
      throw new HttpError(409, `${path}: frontmatter cannot be parsed — fix it first`);
    const [first] = findMentions(content, names, 1);
    if (!first) throw new HttpError(409, 'no plain mention left to link');
    v.write(path, linkMention(content, first, title));
    return c.json({ ok: true, path, line: first.line });
  });

  return app;
}
